### ISSUE TITLE
Sort Criterias

### ISSUE THREAD

**Issue by sebastienserre** [Rarst/release-belt#26]
Hello,
I'm using Release Belft and thank you for this job! it's running like a charm!1 question, on which criterias are sorted the package on homepage?
Not alphabetical, not by date of addition...
I don't find any settings to customize it.

**Comment by Rarst** [comment]
On top of my head it's just what Finder service returns. You could probably play with `finder` service in the container to experiment.

My local copy is messed up at the moment, since I got stuck in the middle of rewriting Silex out. :sweat_smile: 

What are you looking to accomplish with it? Within JSON order doesn't matter really.
