### ISSUE TITLE
Packages.json missing

### ISSUE THREAD

**Issue by sebastienserre** [Rarst/release-belt#28]
Hello, again
I've updated by `composer belt-update` then I have an error ` In RemoteFilesystem.php line 398:
 
   The "https://[public url redacted]/packages.json" file could not be downloa
   ded (HTTP/1.1 404 Not Found)
 `
And no packages.json on public folder. :-/

**Comment by Rarst** [comment]
Do you have web server configured to route through `index.php` ? Could you please double check that?

https://github.com/Rarst/release-belt#3-configure-a-web-server

`packages.json` isn't generated as physical file, so it doesn't appear in `public`. The content for it is generated on the fly by the app.

**Comment by sebastienserre** [comment]
Yes, my subdomain point on `/public` (it worked fine before upgrading), and home page is working:
[image with public URL redacted]

but I've a 404 when clicking on the packages.json on top right

**Comment by Rarst** [comment]
What is your web server and how exactly do you have it set up to route through `index.php` ?

Currently none of the dynamic URLs seems to be reaching the application. Those Not Found responses look like they are coming from web server, not the app.

PS please don't post the public URL to your install, I am sure vendors would appreciate not broadcasting their stuff for free download. :)

**Comment by sebastienserre** [comment]
Is the auth by .htaccess (to avoid your PS remark ;-) ) can break the things in this release ?
My host is o2switch.fr which provide  a cpanel:
https://i.imgur.com/lrDXALW.png

**Comment by Rarst** [comment]
So the web server _needs_ to be configured to point requests at Belt's `public/index.php`. Configuring domain alone doesn't accomplish this, it's just enough for the _root_ of site to work. Because defaulting root to look for `index.php` is a typical default, sending _all_ requests through it is not.

That isn't something Belt by itself can _do_, can _affect_, or subject to _changes_ in its code base (at this time). That is a necessary bit of external configuration to be performed and is specific to the web server.

If you had it previously working, how _did_ you configure this originally? If you didn't at all this can be subject to some kind of defaults on your server.

If you have a managed hosting you might want to consult support on which configuration they suggest.

**Comment by sebastienserre** [comment]
I didn't change anything on my managed hosts
Don't understand why index.php is not loaded.

**Comment by Rarst** [comment]
Well, if you didn't perform this configuration then something else did it for you and maybe it broke as mysteriously as it worked for whatever reason. :)

As per link to readme above, you can refer to Slim docs for recommended configuration:

https://www.slimframework.com/docs/v3/start/web-servers.html#apache-configuration

**Comment by sebastienserre** [comment]
Sorry to bored you, it's OK with rules in .htaccess
maybe I added it in previous config, don't remember and upgrade removed it!

Thx for your great job and patience

**Comment by Rarst** [comment]
I don't _think_ upgrade should have affected it, without git complaining at least, but anyway it should have been in `.gitignore` (old root instance was, new public wasn't) and I updated that accordingly.
