### ISSUE TITLE
URLs in package.json contain authentication information

### ISSUE THREAD

**Issue by swissspidy** [Rarst/release-belt#29]
We use Release Belt with per-user permissions as introduced in #23.

After the update to 0.4.1 (which is not supposed to change any functionality, as far as I can tell) we noticed that a request to `/packages.json` returns `dist` URLs with the authentication information in them.

I don't think this is intentional and I believe the culprit for that is the change from `'schemeAndHttpHost' => $uri->withPath(''),` to `'schemeAndHttpHost' => $uri->withUserInfo(''),` in `IndexModel::getContext()`, see https://github.com/Rarst/release-belt/commit/f32e3c0b2256a4357452bdabca2d67d2403c46c4#diff-7f81e07c70ec9e9f062745fddd9eb252L30

**Comment by Rarst** [comment]
Nulling of user info in index model is actually correct, though I made a switch to generator here to be a little more foolproof.

The bug was in generator itself, since in 0.4 it didn't generate absolute URLs and when that was added it dragged in upstream URI object adding credentials implicitly when used under login.
