### ISSUE TITLE
Type `composer-plugin` not working due to missing `class` element in the `extra` attribute

### ISSUE THREAD

**Issue by grappler** [Rarst/release-belt#45]
Installing a `composer-plugin` from release-belt causes an error
> Error while installing package-name, composer-plugin packages should have a class defined in their extra key to be usable.

The mention `class` is explained here: https://getcomposer.org/doc/articles/plugins.md#plugin-package

I am not sure what the best way of fixing this. The zip file contains a valid `composer.json` which could be parsed but that might be too complicated.

**Comment by Rarst** [comment]
This feels out of scope to me. The goal of Belt to be "Composer repo for ZIPs" can be said in technical speak as "Composer repo for packages where basic composer.json is derived from their archive path and filename, because it's not available (or relevant) inside the package".

Extracting composer.json if it _is_ contained in the package could be a possibility (that's how "normal" Composer repositories/packages work after all), but this can easily conflict with Belt's purpose. Let's say a commercial plugin is _built_ with Composer and includes composer.json, then is distributed as ready-made ZIP file. From Belt perspective the "internal" composer.json _doesn't matter_ and it would be right about that - trying to use it out of intended private build context might very well not work at all.

The reason Belt does this differently is because contained composer.json is supported _natively_ by Composer itself and original repository ecosystem (e.g. Satis). So I had no intention to reinvent things that already had working options.

**Comment by grappler** [comment]
Makes sense 😊

At least with this issue the limitation is somewhat documented.
