### ISSUE TITLE
Composer config fakes PHP version from the environnment

### ISSUE THREAD

**Issue by benoitchantre** [Rarst/release-belt#50]
Is there a reason to define a `platform` with a specific PHP version in `composer.json`?

This removes the checks for the PHP version used by the environnement. If there's an error, the error will happend during runtime instead of being show during the installation of the packages.

**Comment by Rarst** [comment]
So the problem is that dependencies don't care about top-level project's PHP requirements.

In other words, you can have project that purports to run on PHP 7 _with dependencies that don't_. This is increasingly a problem developing in PHP 8+ local environment, but keeping PHP 7 compatibility. It is easy to get `composer.json` and/or `composer.lock` into a state that won't work on PHP 7.

Platform config _somewhat_ addresses that, forcing dependencies selection that _does_ work with lowest supported PHP version. This is less of a nuance with libraries (since when they are required lock is ignored anyway), but I suppose more with a project. I probably just did this out of inertia here.

I am not sure what is _good_ solution in project case. Forcing PHP 7 and lock forces known state on an oldest supported version. I am not sure what's the alternative? Omit lock from version control? No known state then, but can separately unit test 7 and 8 with a matrix.

Opinions welcomed. :)

**Comment by Rarst** [comment]
Ok, I dropped the lock file and split tests into PHP 7/8 in #51, will see how that goes. :)

**Comment by benoitchantre** [comment]
@Rarst Thank you for the explanation, I wasn't aware of all the details.
